Repository DSM-DCS/DCS_Server, pull requests merged in 2022-05, with the labels that each got.

#26 🥀 :: (#24) Security 설정
  build.gradle
  src/main/java/com/dsm/dcs/exception/ExpiredJwtException.java
  src/main/java/com/dsm/dcs/exception/InvalidJwtException.java
  src/main/java/com/dsm/dcs/exception/handler/AuthenticationEntryPointImpl.java
  src/main/java/com/dsm/dcs/security/FilterConfig.java
  src/main/java/com/dsm/dcs/security/SecurityConfig.java
  src/main/java/com/dsm/dcs/security/auth/AuthDetails.java
  src/main/java/com/dsm/dcs/security/auth/AuthDetailsService.java
  src/main/java/com/dsm/dcs/security/jwt/JwtProperties.java
  src/main/java/com/dsm/dcs/security/jwt/JwtTokenFilter.java
  src/main/java/com/dsm/dcs/security/jwt/JwtTokenProvider.java
  src/main/java/com/dsm/dcs/web/WebMvcConfig.java
  src/main/resources/application.yml
Labels: chore

#30 🥀 :: (#29) 회원가입 API
  .github/workflows/build.yml
  src/main/java/com/dsm/dcs/comtroller/UserController.java
  src/main/java/com/dsm/dcs/dto/request/UserSignUpRequest.java
  src/main/java/com/dsm/dcs/dto/response/UserTokenResponse.java
  src/main/java/com/dsm/dcs/entity/Authority.java
  src/main/java/com/dsm/dcs/entity/BaseIdEntity.java
  src/main/java/com/dsm/dcs/entity/BaseTimeEntity.java
  src/main/java/com/dsm/dcs/entity/admin/Admin.java
  src/main/java/com/dsm/dcs/entity/auth/RefreshToken.java
  src/main/java/com/dsm/dcs/entity/auth/RefreshTokenRepository.java
  src/main/java/com/dsm/dcs/entity/user/User.java
  src/main/java/com/dsm/dcs/entity/user/UserRepository.java
  src/main/java/com/dsm/dcs/exception/AccountIdAlreadyExistsException.java
  src/main/java/com/dsm/dcs/exception/EmailAlreadyExistsException.java
  src/main/java/com/dsm/dcs/exception/PasswordMismatchException.java
  src/main/java/com/dsm/dcs/exception/RefreshTokenNotFoundException.java
  src/main/java/com/dsm/dcs/exception/StudentNumberAlreadyExistsException.java
  src/main/java/com/dsm/dcs/exception/UserNotFoundException.java
  src/main/java/com/dsm/dcs/facade/UserFacade.java
  src/main/java/com/dsm/dcs/service/user/UserSignUpService.java
  src/test/java/com/dsm/dcs/DcsApplicationTests.java
Labels: feature

#23 🥀 :: (#19) 택배 배송 정보 등록 구현 기능
  src/main/java/com/dsm/dcs/controller/CourierController.java
  src/main/java/com/dsm/dcs/dto/request/DeliveryListRequest.java
  src/main/java/com/dsm/dcs/dto/response/DeliveryIdListResponse.java
  src/main/java/com/dsm/dcs/entity/BaseIdEntity.java
  src/main/java/com/dsm/dcs/entity/CourierCompany.java
  src/main/java/com/dsm/dcs/entity/delivery/Delivery.java
  src/main/java/com/dsm/dcs/service/CourierService.java
Labels: feature

#32 🥀 :: (#25) Entity 수정
  src/main/java/com/dsm/dcs/dto/request/DeliveryListRequest.java
  src/main/java/com/dsm/dcs/entity/user/User.java
  src/main/java/com/dsm/dcs/service/CourierService.java
Labels: chore, update

#35 🥀 :: (#34) 프로젝트 수정
  src/main/java/com/dsm/dcs/config/WebMvcConfig.java
  src/main/java/com/dsm/dcs/controller/CourierController.java
  src/main/java/com/dsm/dcs/controller/UserController.java
  src/main/java/com/dsm/dcs/entity/delivery/Delivery.java
  src/main/java/com/dsm/dcs/security/SecurityConfig.java
  src/main/java/com/dsm/dcs/service/courier/CourierService.java
Labels: chore, update

#38 🥀 :: (#37) Entity 수정
  src/main/java/com/dsm/dcs/entity/delivery/Delivery.java
  src/main/java/com/dsm/dcs/entity/receipt/Receipt.java
  src/main/java/com/dsm/dcs/entity/receipt/ReceiptRepository.java
  src/main/java/com/dsm/dcs/entity/user/User.java
Labels: chore, update

#33 🥀 :: (#31) 택배 배송 정보 등록 기능 구현
  .github/workflows/build.yml
  build.gradle
  src/main/java/com/dsm/dcs/DcsApplication.java
  src/main/java/com/dsm/dcs/comtroller/UserController.java
  src/main/java/com/dsm/dcs/controller/CourierController.java
  src/main/java/com/dsm/dcs/dto/request/DeliveryListRequest.java
  src/main/java/com/dsm/dcs/dto/request/UserSignUpRequest.java
  src/main/java/com/dsm/dcs/dto/response/DeliveryIdListResponse.java
  src/main/java/com/dsm/dcs/dto/response/UserTokenResponse.java
  src/main/java/com/dsm/dcs/entity/Authority.java
  src/main/java/com/dsm/dcs/entity/BaseIdEntity.java
  src/main/java/com/dsm/dcs/entity/BaseTimeEntity.java
  src/main/java/com/dsm/dcs/entity/admin/Admin.java
  src/main/java/com/dsm/dcs/entity/auth/RefreshToken.java
  src/main/java/com/dsm/dcs/entity/auth/RefreshTokenRepository.java
  src/main/java/com/dsm/dcs/entity/delivery/Delivery.java
  src/main/java/com/dsm/dcs/entity/image/Image.java
  src/main/java/com/dsm/dcs/entity/image/ImageRepository.java
  src/main/java/com/dsm/dcs/entity/receipt/Receipt.java
  src/main/java/com/dsm/dcs/entity/user/User.java
  src/main/java/com/dsm/dcs/entity/user/UserRepository.java
  src/main/java/com/dsm/dcs/exception/AccountIdAlreadyExistsException.java
  src/main/java/com/dsm/dcs/exception/EmailAlreadyExistsException.java
  src/main/java/com/dsm/dcs/exception/ExpiredJwtException.java
  src/main/java/com/dsm/dcs/exception/InvalidJwtException.java
  src/main/java/com/dsm/dcs/exception/PasswordMismatchException.java
  src/main/java/com/dsm/dcs/exception/RefreshTokenNotFoundException.java
  src/main/java/com/dsm/dcs/exception/StudentNumberAlreadyExistsException.java
  src/main/java/com/dsm/dcs/exception/UserNotFoundException.java
  src/main/java/com/dsm/dcs/exception/handler/AuthenticationEntryPointImpl.java
  src/main/java/com/dsm/dcs/facade/UserFacade.java
  src/main/java/com/dsm/dcs/security/FilterConfig.java
  src/main/java/com/dsm/dcs/security/SecurityConfig.java
  src/main/java/com/dsm/dcs/security/auth/AuthDetails.java
  src/main/java/com/dsm/dcs/security/auth/AuthDetailsService.java
  src/main/java/com/dsm/dcs/security/jwt/JwtProperties.java
  src/main/java/com/dsm/dcs/security/jwt/JwtTokenFilter.java
  src/main/java/com/dsm/dcs/security/jwt/JwtTokenProvider.java
  src/main/java/com/dsm/dcs/service/CourierService.java
  src/main/java/com/dsm/dcs/service/user/UserSignUpService.java
  src/main/java/com/dsm/dcs/web/WebMvcConfig.java
  src/main/resources/application.yml
  src/test/java/com/dsm/dcs/DcsApplicationTests.java
Labels: update

#41 🥀 :: (#21) 택배 배송 정보 삭제 기능 구현
  src/main/java/com/dsm/dcs/controller/DeliveryController.java
  src/main/java/com/dsm/dcs/facade/DeliveryFacade.java
  src/main/java/com/dsm/dcs/service/teacher/TeacherService.java
Labels: feature

#42 🥀 :: (#22) 택배 배송 정보
  src/main/java/com/dsm/dcs/controller/CourierController.java
  src/main/java/com/dsm/dcs/controller/DeliveryController.java
  src/main/java/com/dsm/dcs/dto/request/DeliveryListRequest.java
  src/main/java/com/dsm/dcs/dto/response/DeliveryIdListResponse.java
  src/main/java/com/dsm/dcs/entity/CourierCompany.java
  src/main/java/com/dsm/dcs/entity/delivery/Delivery.java
  src/main/java/com/dsm/dcs/entity/user/User.java
  src/main/java/com/dsm/dcs/entity/user/UserRepository.java
  src/main/java/com/dsm/dcs/exception/DeliveryNotFoundException.java
  src/main/java/com/dsm/dcs/facade/DeliveryFacade.java
  src/main/java/com/dsm/dcs/facade/UserFacade.java
  src/main/java/com/dsm/dcs/service/courier/CourierService.java
  src/main/java/com/dsm/dcs/service/teacher/TeacherService.java
  src/main/resources/application.yml
Labels: feature

#43 🥀 :: (#39) User 정보 불러오기
  src/main/java/com/dsm/dcs/controller/UserController.java
  src/main/java/com/dsm/dcs/dto/response/UserListResponse.java
  src/main/java/com/dsm/dcs/entity/user/UserRepository.java
  src/main/java/com/dsm/dcs/facade/UserFacade.java
  src/main/java/com/dsm/dcs/service/user/UserService.java
Labels: feature

#47 🥀 :: (#45) 모든 택배 목록 조회하기
  src/main/java/com/dsm/dcs/controller/DeliveryController.java
  src/main/java/com/dsm/dcs/dto/response/DeliveryListResponse.java
  src/main/java/com/dsm/dcs/entity/delivery/DeliveryRepository.java
  src/main/java/com/dsm/dcs/facade/DeliveryFacade.java
  src/main/java/com/dsm/dcs/service/teacher/TeacherService.java
Labels: feature
