Repository DSM-DCS/DCS_Server, pull requests merged in 2022-06, with the labels that each got.

#56 🥀 :: (#55) Teacher & Courier 회원가입
  src/main/java/com/dsm/dcs/controller/CourierController.java
  src/main/java/com/dsm/dcs/controller/DeliveryController.java
  src/main/java/com/dsm/dcs/controller/TeacherController.java
  src/main/java/com/dsm/dcs/dto/request/CourierSignUpRequest.java
  src/main/java/com/dsm/dcs/dto/request/TeacherSignUpRequest.java
  src/main/java/com/dsm/dcs/entity/Authority.java
  src/main/java/com/dsm/dcs/entity/courier/Courier.java
  src/main/java/com/dsm/dcs/entity/courier/CourierRepository.java
  src/main/java/com/dsm/dcs/entity/delivery/DeliveryRepository.java
  src/main/java/com/dsm/dcs/entity/teacher/Teacher.java
  src/main/java/com/dsm/dcs/entity/teacher/TeacherRepository.java
  src/main/java/com/dsm/dcs/entity/user/User.java
  src/main/java/com/dsm/dcs/exception/CourierNotFoundException.java
  src/main/java/com/dsm/dcs/exception/TeacherNotFoundException.java
  src/main/java/com/dsm/dcs/facade/CourierFacade.java
  src/main/java/com/dsm/dcs/facade/DeliveryFacade.java
  src/main/java/com/dsm/dcs/facade/TeacherFacade.java
  src/main/java/com/dsm/dcs/service/courier/CourierService.java
  src/main/java/com/dsm/dcs/service/courier/CourierSignUpService.java
  src/main/java/com/dsm/dcs/service/teacher/TeacherSignUpService.java
  src/main/java/com/dsm/dcs/service/user/UserService.java
Labels: feature

#59 🥀 :: (#58) Delivery, User List 가져오기 리팩토링
  src/main/java/com/dsm/dcs/controller/DeliveryController.java
  src/main/java/com/dsm/dcs/entity/delivery/DeliveryRepository.java
  src/main/java/com/dsm/dcs/facade/DeliveryFacade.java
  src/main/java/com/dsm/dcs/facade/UserFacade.java
  src/main/java/com/dsm/dcs/service/delivery/DeliveryService.java
  src/main/java/com/dsm/dcs/service/teacher/TeacherService.java
  src/main/java/com/dsm/dcs/service/user/UserService.java
Labels: refactoring

#60 🥀 :: (#57) 택배 상세보기
  src/main/java/com/dsm/dcs/controller/DeliveryController.java
  src/main/java/com/dsm/dcs/dto/response/DeliveryListResponse.java
  src/main/java/com/dsm/dcs/dto/response/DeliveryNullUserListResponse.java
  src/main/java/com/dsm/dcs/facade/DeliveryFacade.java
  src/main/java/com/dsm/dcs/service/delivery/DeliveryService.java
Labels: feature

#62 🥀 :: (#61) JWT refresh토큰 로직 수정
  src/main/java/com/dsm/dcs/controller/AuthController.java
  src/main/java/com/dsm/dcs/controller/CourierController.java
  src/main/java/com/dsm/dcs/controller/TeacherController.java
  src/main/java/com/dsm/dcs/controller/UserController.java
  src/main/java/com/dsm/dcs/dto/TokenDto.java
  src/main/java/com/dsm/dcs/dto/response/UserRefreshTokenResponse.java
  src/main/java/com/dsm/dcs/dto/response/UserTokenResponse.java
  src/main/java/com/dsm/dcs/entity/auth/RefreshToken.java
  src/main/java/com/dsm/dcs/entity/auth/RefreshTokenRepository.java
  src/main/java/com/dsm/dcs/exception/EffectiveJwtException.java
  src/main/java/com/dsm/dcs/exception/NotFindRefreshTokenException.java
  src/main/java/com/dsm/dcs/exception/NotRefreshTokenException.java
  src/main/java/com/dsm/dcs/security/jwt/JwtTokenProvider.java
  src/main/java/com/dsm/dcs/service/auth/TokenRefreshTokenService.java
  src/main/java/com/dsm/dcs/service/auth/UserSignInService.java
  src/main/java/com/dsm/dcs/service/courier/CourierSignUpService.java
  src/main/java/com/dsm/dcs/service/teacher/TeacherSignUpService.java
  src/main/java/com/dsm/dcs/service/user/UserSignUpService.java
Labels: update

#64 🥀 :: (#63) JWT JwtProperties 클래스 수정
  src/main/java/com/dsm/dcs/security/jwt/JwtProperties.java
  src/main/java/com/dsm/dcs/security/jwt/JwtTokenProvider.java
  src/main/java/com/dsm/dcs/service/user/UserSignUpService.java
Labels: update

#66 🥀 :: (#65) JWT 어드민 권한 설정
  src/main/java/com/dsm/dcs/controller/AdminController.java
  src/main/java/com/dsm/dcs/controller/AuthController.java
  src/main/java/com/dsm/dcs/controller/TeacherController.java
  src/main/java/com/dsm/dcs/controller/UserController.java
  src/main/java/com/dsm/dcs/dto/request/LoginRequest.java
  src/main/java/com/dsm/dcs/dto/request/UpdatePasswordRequest.java
  src/main/java/com/dsm/dcs/dto/request/UserLoginRequest.java
  src/main/java/com/dsm/dcs/dto/request/UserSignUpRequest.java
  src/main/java/com/dsm/dcs/dto/request/VerificationAuthCodeRequest.java
  src/main/java/com/dsm/dcs/entity/Authority.java
  src/main/java/com/dsm/dcs/entity/Role.java
  src/main/java/com/dsm/dcs/entity/admin/Admin.java
  src/main/java/com/dsm/dcs/entity/admin/AdminRepository.java
  src/main/java/com/dsm/dcs/entity/auth/RefreshToken.java
  src/main/java/com/dsm/dcs/entity/courier/Courier.java
  src/main/java/com/dsm/dcs/entity/courier/CourierRepository.java
  src/main/java/com/dsm/dcs/entity/teacher/TeacherRepository.java
  src/main/java/com/dsm/dcs/entity/user/User.java
  src/main/java/com/dsm/dcs/entity/user/UserRepository.java
  src/main/java/com/dsm/dcs/exception/AdminNotFoundException.java
  src/main/java/com/dsm/dcs/exception/CourierNotFoundException.java
  src/main/java/com/dsm/dcs/exception/TeacherNotFoundException.java
  src/main/java/com/dsm/dcs/facade/AdminFacade.java
  src/main/java/com/dsm/dcs/facade/CourierFacade.java
  src/main/java/com/dsm/dcs/facade/TeacherFacade.java
  src/main/java/com/dsm/dcs/security/auth/AuthDetails.java
  src/main/java/com/dsm/dcs/security/jwt/JwtTokenProvider.java
  src/main/java/com/dsm/dcs/service/admin/AdminAuthService.java
  src/main/java/com/dsm/dcs/service/auth/TokenRefreshTokenService.java
  src/main/java/com/dsm/dcs/service/auth/UserSignInService.java
  src/main/java/com/dsm/dcs/service/courier/CourierSignUpService.java
  src/main/java/com/dsm/dcs/service/teacher/TeacherSignUpService.java
  src/main/java/com/dsm/dcs/service/user/SearchAccountIdService.java
  src/main/java/com/dsm/dcs/service/user/UserAuthService.java
Labels: update

#74 🥀 :: (#72) 선생님 공지 게시판 수정 기능 구현
  src/main/java/com/dsm/dcs/controller/PostController.java
  src/main/java/com/dsm/dcs/entity/post/Post.java
  src/main/java/com/dsm/dcs/exception/PostNotFoundException.java
  src/main/java/com/dsm/dcs/facade/PostFacade.java
  src/main/java/com/dsm/dcs/service/post/PostService.java
Labels: feature

#78 🥀 :: (#70) 코드 리팩토링과 코드 수정
  src/main/java/com/dsm/dcs/controller/AuthController.java
  src/main/java/com/dsm/dcs/controller/DeliveryController.java
  src/main/java/com/dsm/dcs/dto/request/CourierSignUpRequest.java
  src/main/java/com/dsm/dcs/dto/request/DeliveryListRequest.java
  src/main/java/com/dsm/dcs/dto/request/LoginRequest.java
  src/main/java/com/dsm/dcs/dto/request/UserSignUpRequest.java
  src/main/java/com/dsm/dcs/dto/request/VerificationAuthCodeRequest.java
  src/main/java/com/dsm/dcs/dto/request/VerificationPasswordRequest.java
  src/main/java/com/dsm/dcs/dto/response/DeliveryListResponse.java
  src/main/java/com/dsm/dcs/dto/response/DeliveryNullUserListResponse.java
  src/main/java/com/dsm/dcs/dto/response/DeliveryResponse.java
  src/main/java/com/dsm/dcs/entity/user/UserRepository.java
  src/main/java/com/dsm/dcs/facade/DeliveryFacade.java
  src/main/java/com/dsm/dcs/facade/UserFacade.java
  src/main/java/com/dsm/dcs/service/auth/CheckEmailExistsService.java
  src/main/java/com/dsm/dcs/service/auth/CheckExistsService.java
  src/main/java/com/dsm/dcs/service/auth/CheckPhoneNumberExistsService.java
  src/main/java/com/dsm/dcs/service/auth/CheckStudentNumberExistsService.java
  src/main/java/com/dsm/dcs/service/auth/CheckUserExistsService.java
  src/main/java/com/dsm/dcs/service/delivery/DeliveryService.java
  src/main/java/com/dsm/dcs/service/user/UserService.java
Labels: update, refactoring

#80 🥀 :: (#76) 선생님 공지사항 목록보기 기능 구현
  src/main/java/com/dsm/dcs/controller/PostController.java
  src/main/java/com/dsm/dcs/dto/response/PostListResponse.java
  src/main/java/com/dsm/dcs/entity/post/PostRepository.java
  src/main/java/com/dsm/dcs/facade/PostFacade.java
  src/main/java/com/dsm/dcs/service/post/PostService.java
Labels: feature

#79 🥀 :: (#75) 선생님 공지 게시판 삭제 기능 구현
  src/main/java/com/dsm/dcs/controller/PostController.java
  src/main/java/com/dsm/dcs/service/post/PostService.java
Labels: feature

#81 🥀 :: (#77) 선생님 공지사항 게시글 상세보기 기능 구현
  src/main/java/com/dsm/dcs/controller/PostController.java
  src/main/java/com/dsm/dcs/dto/response/PostResponse.java
  src/main/java/com/dsm/dcs/service/post/PostService.java
Labels: feature

#83 🥀 :: (#82) 서비스 리팩토링 및 Exception 설정 변경
  src/main/java/com/dsm/dcs/error/CustomAuthenticationEntryPoint.java
  src/main/java/com/dsm/dcs/error/ErrorResponse.java
  src/main/java/com/dsm/dcs/error/ExceptionFilter.java
  src/main/java/com/dsm/dcs/error/GlobalExceptionHandler.java
  src/main/java/com/dsm/dcs/error/exception/DcsException.java
  src/main/java/com/dsm/dcs/error/exception/ErrorCode.java
  src/main/java/com/dsm/dcs/exception/AccountIdAlreadyExistsException.java
  src/main/java/com/dsm/dcs/exception/AccountIdExistsException.java
  src/main/java/com/dsm/dcs/exception/AdminNotFoundException.java
  src/main/java/com/dsm/dcs/exception/AuthCodeAlreadyVerifiedException.java
  src/main/java/com/dsm/dcs/exception/AuthCodeRequestOverLimitException.java
  src/main/java/com/dsm/dcs/exception/DeliveryNotFoundException.java
  src/main/java/com/dsm/dcs/exception/EffectiveJwtException.java
  src/main/java/com/dsm/dcs/exception/EmailAlreadyExistsException.java
  src/main/java/com/dsm/dcs/exception/EmailExistsException.java
  src/main/java/com/dsm/dcs/exception/ExpiredJwtException.java
  src/main/java/com/dsm/dcs/exception/InvalidAuthCodeException.java
  src/main/java/com/dsm/dcs/exception/InvalidJwtException.java
  src/main/java/com/dsm/dcs/exception/InvalidRoleException.java
  src/main/java/com/dsm/dcs/exception/NotFindRefreshTokenException.java
  src/main/java/com/dsm/dcs/exception/NotRefreshTokenException.java
  src/main/java/com/dsm/dcs/exception/PasswordMismatchException.java
  src/main/java/com/dsm/dcs/exception/PhoneNumberAlreadyExistsException.java
  src/main/java/com/dsm/dcs/exception/PhoneNumberExistsException.java
  src/main/java/com/dsm/dcs/exception/PostNotFoundException.java
  src/main/java/com/dsm/dcs/exception/RefreshTokenNotFoundException.java
  src/main/java/com/dsm/dcs/exception/StudentNumberAlreadyExistsException.java
  src/main/java/com/dsm/dcs/exception/StudentNumberExistsException.java
  src/main/java/com/dsm/dcs/exception/UnVerifiedAuthCodeException.java
  src/main/java/com/dsm/dcs/exception/UserAlreadyExistsException.java
  src/main/java/com/dsm/dcs/exception/UserAuthCodeNotFoundException.java
  src/main/java/com/dsm/dcs/exception/UserExistsException.java
  src/main/java/com/dsm/dcs/exception/UserNotFoundException.java
  src/main/java/com/dsm/dcs/exception/handler/AuthenticationEntryPointImpl.java
  src/main/java/com/dsm/dcs/exception/handler/DcsException.java
  src/main/java/com/dsm/dcs/exception/handler/DcsExceptionFilter.java
  src/main/java/com/dsm/dcs/exception/handler/ErrorResponse.java
  src/main/java/com/dsm/dcs/facade/AdminFacade.java
  src/main/java/com/dsm/dcs/facade/UserFacade.java
  src/main/java/com/dsm/dcs/security/FilterConfig.java
  src/main/java/com/dsm/dcs/security/SecurityConfig.java
  src/main/java/com/dsm/dcs/security/auth/AuthDetails.java
  src/main/java/com/dsm/dcs/security/jwt/JwtTokenProvider.java
  src/main/java/com/dsm/dcs/service/auth/TokenRefreshTokenService.java
Labels: refactoring

#85 🥀 :: (#84) user 정보 상세보기
  src/main/java/com/dsm/dcs/controller/UserController.java
  src/main/java/com/dsm/dcs/dto/response/UserResponse.java
  src/main/java/com/dsm/dcs/service/user/UserService.java
Labels: feature

#91 🥀 :: (#87) 토큰 재발급 로직 수정
  src/main/java/com/dsm/dcs/security/jwt/JwtTokenFilter.java
  src/main/java/com/dsm/dcs/security/jwt/JwtTokenProvider.java
  src/main/java/com/dsm/dcs/service/auth/TokenRefreshTokenService.java
Labels: update

#89 🥀 :: (#86) 로그아웃 구현
  src/main/java/com/dsm/dcs/controller/UserController.java
  src/main/java/com/dsm/dcs/service/user/UserAuthService.java
Labels: feature
